### ISSUE TITLE
Add Dr. Dennis Wang in Mentors section

### ISSUE THREAD

**Issue by szen95** [szen95/hackmed.github.io#10]
Use photo from SITraN link below.

Short bio (feel free to make edits):
Lecturer in Bioinformatics, Co-Director of Postgraduate Programme in Genomic Medicine at TUoS. He has 12 years of experience developing software solutions for biomedical labs and hospitals. Educator of genomics and data science for medicine. Advises several pharmaceutical and biotech companies.

SITraN link:
http://sitran.org/people/wang/

LinkedIn:
https://uk.linkedin.com/in/dennis-wang-77378828

**Comment by jchui** [comment]
Added in latest commit.
